package strategy

import (
	"trading-bot/internal/trading/domain"
)

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	Action     string  `json:"action"` // e.g., "ADJUST_POSITION_SIZE"
	Multiplier float64 `json:"multiplier"`
}

// Strategy is an interface for defining adaptive trading strategies.
// The Execute method takes the current rolling metrics as input and returns a signal.
type Strategy interface {
	Execute(candles []domain.Candle) *Signal
}

// SimpleAdaptiveStrategy is a simple adaptive strategy that adjusts the position size
// based on the recent win rate.
type SimpleAdaptiveStrategy struct{}

// Execute implements the Strategy interface.
// It returns a signal to increase the position size if the win rate is above 60%,
// and a signal to decrease the position size if the win rate is below 40%.
func (s *SimpleAdaptiveStrategy) Execute(candles []domain.Candle) *Signal {
	// TODO: Implement the adaptive strategy
	return nil
}
